#!/usr/bin/env sh

./make_style.sh
echo yes | python3 manage.py collectstatic
python3 manage.py compilemessages
python3 manage.py compilejsi18n

/wait

python3 manage.py migrate --noinput

service redis-server start

/bin/bash -s # temporary command to hold open the container for debugging

#/usr/bin/supervisord -n
