#!/usr/bin/env sh

./make_style.sh
python3 manage.py collectstatic --noinput
python3 manage.py compilemessages
python3 manage.py compilejsi18n

/wait

python3 manage.py migrate --noinput

service redis-server start

/usr/bin/supervisord -n
